version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - backend

    backend:
        build:
            context: backend/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./backend:/app
        depends_on:
            - backend-php-fpm
        env_file:
            - .env.local

    backend-php-fpm:
        build:
            context: backend/docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./backend:/app
        env_file:
            - .env.local

    backend-php-cli:
        build:
            context: backend/docker
            dockerfile: development/php-cli/Dockerfile
        volumes:
            - ./backend:/app
        env_file:
            - .env.local

    swiperead-db:
        image: postgres:13-alpine
        env_file:
            - .env.local
        volumes:
            - swiperead-db:/var/lib/postgresql/data
        ports:
            - "15432:5432"

    frontend:
        build:
            context: frontend/docker/development/nginx
        depends_on:
            - frontend-node
        env_file:
            - .env.local

    frontend-node:
        build:
            context: frontend/docker/development/node
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && ng run swiperead:serve --port=8080 --host 0.0.0.0"
        volumes:
            - ./frontend:/app
        tty: true
        env_file:
            - .env.local

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

volumes:
    swiperead-db:
